# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://chiron19.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Chiron's Space"
description: Chiron's Personal Website, A Github Pages (Jekyll) based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: 
  name: Ziyang Song
  image: head.jpeg  # file must be in the /assets/img/ folder
author-bio: The first and best victory is to conquer self.<br><i>—Plato</i>
# Master's student in Information and Network <span style="white-space: no-wrap;">Engineering (EECS, KTH),</span><br>Ongoing master thesis project "<i>A New Privacy-Federated Learning Framework for Simulating User Interactions</i>" # change to false to hide
image: ./assets/img/head.jpeg


# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog
- text: Workspace
  permalink: workspace

# use false to turn off any social media links
twitter: false
facebook: https://facebook.com/chiron.ziyang.song
instagram: https://instagram.com/chiron_zy
github: https://github.com/Chiron19
linkedin: https://linkedin.com/in/ziyang-song
medium: false
google-scholar: false
email: mailto:ziyang_song@outlook.com
rss: ./feed.xml

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/Chiron19/Chiron19.github.io

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
    - jekyll-feed

# collections
collections:
  tweets:
    output: true

# jekyll-feed
feed:
  posts_limit: 10
  categories:
    - tweets
  collections:
    - posts
    - tweets
