# change the followings to match your Github username and repo name
baseurl: "" # the name of your github repo
url: "https://chiron19.github.io" # the url of your github pages

# site information used in page title, meta data etc.
title: "Chiron's Space"
description: A Github Pages (Jekyll) template based on TailwindCSS

# color theme for links
theme-color: indigo # indigo|yellow|pink|green|stone|

# homepage information
author: Ziyang Song
author-bio: Master's student in Information and Network Engineering (EECS, KTH),<br>Ongoing master thesis project "<i>A New Privacy-Federated Learning Framework for Simulating User Interactions</i>" # change to false to hide
author-image: AI_pic.jpg  # file must be in the /assets/img/ folder

# navigation menu
show-nav-menu: true

nav-menu:
- text: About
  permalink: about
- text: Blog
  permalink: blog
- text: Workspace
  permalink: workspace

# use false to turn off any social media links
twitter: false
facebook: https://facebook.com/chiron.ziyang.song
instagram: https://instagram.com/chiron_zy
github: https://github.com/Chiron19
linkedin: https://linkedin.com/in/ziyang-song
medium: false
google-scholar: false
email: mailto:ziyang_song@outlook.com

# footer information
footer-msg: "Powered by Tailpages"
footer-msg-link: https://github.com/harrywang/tailpages

# google analytics
google-analytics: G-WCRC1TC2V5

# jekyll plugins - no need to change
plugins:
    - jekyll-seo-tag
